/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness / readiness + Alpaca холболтын төлөв */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Дансны хормын хувилбар (Alpaca-ийн буцаасан утга, өөрчлөлтгүй)
         * @description AC-1: талбар бүр Alpaca REST-ийн хариунаас ШУУД гарна. Backend нь
         *     equity, buying power зэргийг локалаар ХЭЗЭЭ Ч дахин тооцохгүй.
         */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Нээлттэй позицууд (origin-той) */
        get: operations["getPositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/quote/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Сүүлийн quote (илгээхээс өмнөх notional-ийн эх сурвалж)
         * @description LLD §16.5 — гарын ticket дээрх «тооцоолсон notional» нь ЭНЭ утгаас
         *     бодогдоно, operator-ийн бичсэн үнээс БИШ. Quote хуучирсан бол
         *     `stale: true` — далдлахгүй. Quote огт байхгүй бол 503, таамагласан
         *     үнэ ХЭЗЭЭ Ч буцаахгүй.
         */
        get: operations["getQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order-ийн түүх */
        get: operations["getOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Operator-ийн гараар илгээх order (FR-12, AC-31…AC-33)
         * @description Agent-ийн order-той ЯГ ИЖИЛ зам: Risk Agent → Execution → Alpaca.
         *     Тусдаа, хаалтгүй зам БАЙХГҮЙ.
         *
         *     **Төлөвийн хараат байдал (AC-33):**
         *     - `halted`        → 409 `system_halted`, Alpaca руу 0 дуудалт.
         *     - `winding_down`  → зөвхөн эрсдэл БАГАСГАХ order; нэмэгдүүлэх нь
         *                         422 `winding_down_increase_blocked`.
         *     - `active`        → Risk-ийн ердийн шалгалт.
         *
         *     **Хоёр шаттай баталгаажуулалт:** Risk `ESCALATE_TO_HUMAN` буцаавал
         *     (жишээ нь notional > `MAX_ORDER_NOTIONAL`) backend нь 409 +
         *     `confirmation` объект буцаана. Дуудагч ЯГ ижил биеийг
         *     `confirmation_token`-той дахин илгээнэ. Approval queue-д мөр
         *     ҮҮСГЭХГҮЙ — operator өөрөө шууд энд байна (спек A-8).
         */
        post: operations["postOrdersManual"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Нээлттэй order-ыг цуцлах (хүний үйлдэл)
         * @description Цуцлалт нь эрсдэл БАГАСГАХ үйлдэл тул `winding_down` үед
         *     зөвшөөрөгдөнө. `halted` үед МӨН зөвшөөрөгдөнө — kill switch нь
         *     ШИНЭ order илгээхийг зогсоодог, байгаа order-ыг цуцлахыг биш
         *     (спек A-2).
         */
        post: operations["postOrdersByOrderIdCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * «Хэн юунд арилжаа хийж байна» (FR-11, AC-30)
         * @description Гаралт нь `orders` / `positions`-ийн БОДИТ мөрөөс угсарна. Тусдаа
         *     тооцоолсон кэш БАЙХГҮЙ — тиймээс энд гарсан symbol бүр дор хаяж
         *     нэг мөрөнд буцаж холбогдоно.
         */
        get: operations["getAttribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Зөвшөөрөл хүлээж буй саналууд */
        get: operations["getApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approvalId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Хүлээгдэж буй саналыг зөвшөөрөх */
        post: operations["postApprovalsByApprovalIdApprove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{approvalId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Хүлээгдэж буй саналыг татгалзах (буцаах боломжгүй) */
        post: operations["postApprovalsByApprovalIdReject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent-ийн шийдвэрийн лог (шүүлттэй) */
        get: operations["getAgentDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-decisions/{decisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Нэг шийдвэр — ТҮҮХИЙ tool call payload-той хамт (AC-7, AC-8)
         * @description `tool_calls[].request` / `.response` нь Alpaca-аас ирсэн байдлаараа,
         *     redaction-аас өөр ямар ч засваргүй. Энэ нь «AI яагаад ингэж хэлсэн
         *     бэ» гэдгийн эх сурвалж — дүгнэлт биш, өгөгдөл.
         */
        get: operations["getAgentDecisionsByDecisionId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Тохируулагдсан LLM provider-ууд ба role тус бүрийн идэвхтэй нь */
        get: operations["getProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{role}/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Role-ийн provider-ыг ажиллаж байхад нь солих (FR-8, AC-10)
         * @description Restart БАЙХГҮЙ. Нислэг дунд байгаа tool call-ууд хуучин provider-оор
         *     дуусч, ХУУЧНААР нь бүртгэгдэнэ; солилтоос ХОЙШ эхэлсэн session нь
         *     шинэ provider-т онооно. v1-д `role` = `research` л боломжтой
         *     (спек A-3: бусад agent LLM биш).
         */
        post: operations["postProvidersByRoleSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuning/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whitelist параметр, тэдгээрийн муж, одоогийн утга, түүх
         * @description Энэ API-д whitelist эсвэл bounds-ыг ӨӨРЧЛӨХ endpoint ЗОРИУДААР
         *     БАЙХГҮЙ (T-26, AC-24). Муж нь config-оос — deploy-ээр л солигдоно.
         */
        get: operations["getTuningParameters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tuning/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Paper-т шалгагдсан параметрийн багцыг live рүү дэвшүүлэх (AC-23)
         * @description Хоёр шаттай баталгаажуулалт заавал (409 → `confirmation_token`).
         */
        post: operations["postTuningPromote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Арилжааны төлөвийн машины одоогийн байдал (FR-13) */
        get: operations["getSystemState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ЗОГСОО — шинэ order илгээхийг ТЭР ДОР НЬ зогсоох (FR-7, AC-14)
         * @description Төлөв → `halted`, 1 секунд дотор. Байгаа позицыг АВТОМАТААР ХААХГҮЙ
         *     (спек A-2). Идемпотент: аль хэдийн `halted` бол 200 буцаана.
         *     Энэ дуудалт баталгаажуулалт ШААРДАХГҮЙ — яаралтай хаалтын замд
         *     саад тавихгүй.
         */
        post: operations["postKillSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/wind-down": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * УНТРААХ БЭЛТГЭЛ — эхлээд хаах цонх, дараа нь зогсох (FR-13, AC-34)
         * @description Төлөв → `winding_down`, 1 секунд дотор, `system` WS сувгаар түгээнэ.
         *     `wind_down_deadline = now + WIND_DOWN_GRACE` (хуанлийн цагаар).
         *     Grace дуусахад автоматаар `halted` (AC-36).
         *
         *     Энэ үед: эрсдэл нэмэгдүүлэх бүх order татгалзана; хаах / багасгах
         *     order дамжина. Позиц АВТОМАТААР хаагдахгүй (спек A-7) — agent ба
         *     operator-т хаах БОЛОМЖ өгч байгаа, албадан зарахгүй.
         */
        post: operations["postSystemWindDown"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ИДЭВХЖҮҮЛ — `ACTIVE` руу буцах ЦОРЫН ГАНЦ зам (AC-37)
         * @description Хоёр шаттай баталгаажуулалт ЗААВАЛ. Түүнчлэн backend нь circuit
         *     breaker-ийн бүх метрикийг ДАХИН ҮНЭЛНЭ — аль нэг нь босгоосоо дээр
         *     хэвээр бол 409, аль метрик болохыг нэрлэж буцаана. Энэ нь
         *     «цэвэрлэсэн» гэсэн туг БИШ, БОДИТ хэмжилт — тугийг гараар асаах
         *     замаар тойрох боломжгүй.
         */
        post: operations["postSystemActivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Fixed-point decimal тэмдэгт мөр. Float ХЭЗЭЭ Ч биш (AC-25).
         * @example 10234.56
         * @example -42.00
         */
        Money: string;
        /** @description Ширхэг. Crypto-д бутархай байж болох тул decimal тэмдэгт мөр. */
        Quantity: string;
        /**
         * Format: date-time
         * @description RFC 3339, ЗААВАЛ UTC (`Z`). Локал бүс хориотой (AC-26).
         */
        Utc: string;
        /**
         * @description Энэ хариун дахь БҮХ өгөгдлийн гарал. Нэг хариу дотор холимог утга
         *     БАЙХГҮЙ — холих шаардлагатай бол тусдаа хүсэлт (AC-20, AC-21).
         * @enum {string}
         */
        Source: "alpaca_live" | "alpaca_paper" | "backtest";
        /** @enum {string} */
        SystemState: "active" | "winding_down" | "halted";
        /**
         * @description Order / позицийн гарал үүсэл (AC-29). `external` = локал `orders`-д
         *     таарах бичлэг ОЛДООГҮЙ (Alpaca UI-аас нээсэн г.м.). ХЭЗЭЭ Ч
         *     таамаглахгүй — таарахгүй бол `external`.
         * @enum {string}
         */
        Origin: "research_agent" | "auto_tuning" | "manual_operator" | "external";
        /** @enum {string} */
        RiskDecision: "APPROVE" | "REJECT" | "ESCALATE_TO_HUMAN";
        /** @enum {string} */
        OrderSide: "buy" | "sell";
        /** @enum {string} */
        OrderType: "market" | "limit" | "stop" | "stop_limit" | "bracket";
        /** @enum {string} */
        TimeInForce: "day" | "gtc" | "ioc" | "fok";
        Envelope: {
            source: components["schemas"]["Source"];
            as_of: components["schemas"]["Utc"];
            /**
             * @description Өгөгдөл `STALE_AFTER_SECONDS`-оос хуучин. Талбарыг ОРХИХГҮЙ —
             *     ил `false` бичнэ (хавсралт 10 §2.4: «байхгүй» нь таамаглах цонх).
             * @default false
             */
            stale: boolean;
            system_state: components["schemas"]["SystemState"];
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "status": "ok",
         *       "broker": {
         *         "name": "alpaca_paper",
         *         "reachable": true,
         *         "last_ok_at": "2026-09-16T14:29:58Z"
         *       },
         *       "database": {
         *         "name": "postgres",
         *         "reachable": true,
         *         "last_ok_at": "2026-09-16T14:29:59Z"
         *       },
         *       "redis": {
         *         "name": "redis",
         *         "reachable": true,
         *         "last_ok_at": "2026-09-16T14:29:59Z"
         *       },
         *       "providers": [
         *         {
         *           "name": "claude-mcp",
         *           "reachable": true,
         *           "last_ok_at": "2026-09-16T14:28:11Z"
         *         },
         *         {
         *           "name": "gpt-fc",
         *           "reachable": true,
         *           "last_ok_at": "2026-09-16T14:27:40Z"
         *         }
         *       ]
         *     }
         */
        Health: components["schemas"]["Envelope"] & {
            /** @enum {string} */
            status: "ok" | "degraded" | "down";
            broker: components["schemas"]["Dependency"];
            database: components["schemas"]["Dependency"];
            redis: components["schemas"]["Dependency"];
            providers: components["schemas"]["Dependency"][];
        };
        Dependency: {
            name: string;
            reachable: boolean;
            last_ok_at?: components["schemas"]["Utc"];
            detail?: string;
        };
        Account: {
            account_id: string;
            equity: components["schemas"]["Money"];
            cash: components["schemas"]["Money"];
            buying_power: components["schemas"]["Money"];
            last_equity?: components["schemas"]["Money"];
            pattern_day_trader: boolean;
            day_trade_count: number;
            trading_blocked?: boolean;
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "account": {
         *         "account_id": "PA3X9QK2TLZ0",
         *         "equity": "104238.17",
         *         "cash": "38210.55",
         *         "buying_power": "76421.10",
         *         "last_equity": "103980.44",
         *         "pattern_day_trader": false,
         *         "day_trade_count": 1,
         *         "trading_blocked": false
         *       }
         *     }
         */
        AccountEnvelope: components["schemas"]["Envelope"] & {
            account: components["schemas"]["Account"];
        };
        Quote: {
            symbol: string;
            bid: components["schemas"]["Money"];
            ask: components["schemas"]["Money"];
            last: components["schemas"]["Money"];
            quote_ts: components["schemas"]["Utc"];
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "quote": {
         *         "symbol": "AAPL",
         *         "bid": "221.48",
         *         "ask": "221.52",
         *         "last": "221.50",
         *         "quote_ts": "2026-09-16T14:29:58Z"
         *       }
         *     }
         */
        QuoteEnvelope: components["schemas"]["Envelope"] & {
            quote: components["schemas"]["Quote"];
        };
        Position: {
            symbol: string;
            qty: components["schemas"]["Quantity"];
            /** @enum {string} */
            side: "long" | "short";
            avg_entry_price: components["schemas"]["Money"];
            market_value: components["schemas"]["Money"];
            unrealized_pl: components["schemas"]["Money"];
            origin: components["schemas"]["Origin"];
            /** @description `research_agent` үед provider/model; `manual_operator` үед actor; `external` үед `null`. */
            origin_detail?: string | null;
            /** @description Энэ symbol дээр НЭГЭЭС ОЛОН origin fill хийсэн (LLD §11.1). `origin` нь сүүлийн fill-ийнх — бүтэн задаргаа БИШ. UI үүнийг ил тэмдэглэнэ, далдлахгүй (LLD §16.4). */
            origin_mixed: boolean;
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "positions": [
         *         {
         *           "symbol": "AAPL",
         *           "qty": "40",
         *           "side": "long",
         *           "avg_entry_price": "221.40",
         *           "market_value": "9012.00",
         *           "unrealized_pl": "156.00",
         *           "origin": "research_agent",
         *           "origin_detail": "claude-mcp/claude-opus-5",
         *           "origin_mixed": false
         *         },
         *         {
         *           "symbol": "MSFT",
         *           "qty": "12",
         *           "side": "long",
         *           "avg_entry_price": "402.10",
         *           "market_value": "4870.80",
         *           "unrealized_pl": "-54.40",
         *           "origin": "manual_operator",
         *           "origin_detail": "operator",
         *           "origin_mixed": true
         *         },
         *         {
         *           "symbol": "TSLA",
         *           "qty": "5",
         *           "side": "long",
         *           "avg_entry_price": "248.90",
         *           "market_value": "1252.50",
         *           "unrealized_pl": "8.00",
         *           "origin": "external",
         *           "origin_detail": null,
         *           "origin_mixed": false
         *         }
         *       ]
         *     }
         */
        PositionsEnvelope: components["schemas"]["Envelope"] & {
            positions: components["schemas"]["Position"][];
        };
        Order: {
            /**
             * Format: uuid
             * @description Локал ID
             */
            id: string;
            /** @description Alpaca-ийн ID; илгээгдэх хүртэл `null` */
            broker_order_id?: string | null;
            /** @description Idempotency түлхүүрээс гаргасан детерминистик ID */
            client_order_id: string;
            symbol: string;
            side: components["schemas"]["OrderSide"];
            qty: components["schemas"]["Quantity"];
            filled_qty?: components["schemas"]["Quantity"];
            order_type: components["schemas"]["OrderType"];
            limit_price?: components["schemas"]["Money"];
            stop_price?: components["schemas"]["Money"];
            time_in_force?: components["schemas"]["TimeInForce"];
            /** @enum {string} */
            status: "pending_risk" | "pending_approval" | "rejected" | "accepted" | "partially_filled" | "filled" | "canceled" | "expired" | "failed";
            origin: components["schemas"]["Origin"];
            origin_detail?: string | null;
            /**
             * Format: uuid
             * @description Холбогдох `agent_decisions` мөр
             */
            decision_id?: string | null;
            submitted_at: components["schemas"]["Utc"];
            /** @description Биелэх хүртэл `null` */
            filled_at?: components["schemas"]["Utc"] | null;
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "orders": [
         *         {
         *           "id": "6f1b5a2c-0d4e-4f31-9b77-1a2c3d4e5f60",
         *           "broker_order_id": "0b6c9a51-4e2f-4a1d-9f0c-7d8e9f0a1b2c",
         *           "client_order_id": "p3-6f1b5a2c",
         *           "symbol": "AAPL",
         *           "side": "buy",
         *           "qty": "10",
         *           "filled_qty": "10",
         *           "order_type": "limit",
         *           "limit_price": "221.50",
         *           "time_in_force": "day",
         *           "status": "filled",
         *           "origin": "research_agent",
         *           "origin_detail": "claude-mcp/claude-opus-5",
         *           "decision_id": "3c9d8e7f-6a5b-4c3d-8e1f-0a9b8c7d6e5f",
         *           "submitted_at": "2026-09-16T13:55:02Z",
         *           "filled_at": "2026-09-16T13:55:04Z"
         *         },
         *         {
         *           "id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d",
         *           "broker_order_id": null,
         *           "client_order_id": "p3-9a8b7c6d",
         *           "symbol": "MSFT",
         *           "side": "sell",
         *           "qty": "12",
         *           "filled_qty": "0",
         *           "order_type": "market",
         *           "time_in_force": "day",
         *           "status": "pending_risk",
         *           "origin": "manual_operator",
         *           "origin_detail": "operator",
         *           "decision_id": null,
         *           "submitted_at": "2026-09-16T14:29:51Z"
         *         }
         *       ]
         *     }
         */
        OrdersEnvelope: components["schemas"]["Envelope"] & {
            orders: components["schemas"]["Order"][];
        };
        ManualOrderRequest: {
            symbol: string;
            side: components["schemas"]["OrderSide"];
            qty: components["schemas"]["Quantity"];
            order_type: components["schemas"]["OrderType"];
            time_in_force: components["schemas"]["TimeInForce"];
            limit_price?: components["schemas"]["Money"];
            stop_price?: components["schemas"]["Money"];
            /**
             * @description Зөвхөн өмнөх 409 `confirmation_required` хариунаас авсан утга.
             *     `grounded_in` / `rationale` ЭНД БАЙХГҮЙ — гарын order нь agent-ийн
             *     санал БИШ, grounding checker хамаарахгүй (AC-32).
             */
            confirmation_token?: string;
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "order": {
         *         "id": "9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d",
         *         "broker_order_id": null,
         *         "client_order_id": "p3-9a8b7c6d",
         *         "symbol": "MSFT",
         *         "side": "sell",
         *         "qty": "12",
         *         "filled_qty": "0",
         *         "order_type": "market",
         *         "time_in_force": "day",
         *         "status": "accepted",
         *         "origin": "manual_operator",
         *         "origin_detail": "operator",
         *         "decision_id": null,
         *         "submitted_at": "2026-09-16T14:29:51Z"
         *       },
         *       "risk": {
         *         "decision": "APPROVE",
         *         "reason": null,
         *         "evaluated_at": "2026-09-16T14:29:51Z",
         *         "checks": [
         *           {
         *             "rule": "system_state",
         *             "passed": true,
         *             "limit_name": "SYSTEM_STATE",
         *             "limit_value": "active",
         *             "actual_value": "active"
         *           },
         *           {
         *             "rule": "order_notional",
         *             "passed": true,
         *             "limit_name": "MAX_ORDER_NOTIONAL",
         *             "limit_value": "5000.00",
         *             "actual_value": "4870.80"
         *           },
         *           {
         *             "rule": "wind_down_direction",
         *             "passed": true,
         *             "detail": "Позиц хаах чиглэл — winding_down үед ч зөвшөөрөгдөнө"
         *           }
         *         ]
         *       }
         *     }
         */
        OrderAccepted: components["schemas"]["Envelope"] & {
            order: components["schemas"]["Order"];
            risk: components["schemas"]["RiskEvaluation"];
        };
        RiskEvaluation: {
            decision: components["schemas"]["RiskDecision"];
            reason?: string | null;
            evaluated_at: components["schemas"]["Utc"];
            /** @description Шалгалт бүрийн үр дүн — юу унасныг, ямар хязгаартай харьцуулснаар нь ил харуулна. */
            checks: {
                /** @enum {string} */
                rule: "system_state" | "restricted_symbol" | "position_pct" | "total_exposure_pct" | "daily_loss_limit" | "pdt_day_trades" | "order_notional" | "price_sanity" | "wind_down_direction";
                passed: boolean;
                /** @description config-ийн нэр, жишээ: `MAX_POSITION_PCT` */
                limit_name?: string;
                limit_value?: string;
                actual_value?: string;
                detail?: string;
            }[];
        };
        Approval: {
            /** Format: uuid */
            id: string;
            version: number;
            /** @enum {string} */
            state: "pending" | "approved" | "rejected" | "expired";
            /** Format: uuid */
            decision_id: string;
            proposed_order: components["schemas"]["ProposedOrder"];
            risk: components["schemas"]["RiskEvaluation"];
            created_at: components["schemas"]["Utc"];
            /** @description `created_at + APPROVAL_TTL`. Дараа нь автоматаар `expired` (AC-6). */
            expires_at: components["schemas"]["Utc"];
            /** @description Шийдэгдэх хүртэл `null` */
            resolved_at?: components["schemas"]["Utc"] | null;
            resolution_reason?: string | null;
        };
        ProposedOrder: {
            symbol: string;
            side: components["schemas"]["OrderSide"];
            qty: components["schemas"]["Quantity"];
            order_type: components["schemas"]["OrderType"];
            limit_price?: components["schemas"]["Money"];
            stop_price?: components["schemas"]["Money"];
            estimated_notional?: components["schemas"]["Money"];
            rationale: string;
            grounded_in: string[];
            provider: string;
            model: string;
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "approvals": [
         *         {
         *           "id": "2d3e4f50-6172-4839-a0b1-c2d3e4f50617",
         *           "version": 1,
         *           "state": "pending",
         *           "decision_id": "3c9d8e7f-6a5b-4c3d-8e1f-0a9b8c7d6e5f",
         *           "proposed_order": {
         *             "symbol": "NVDA",
         *             "side": "buy",
         *             "qty": "25",
         *             "order_type": "limit",
         *             "limit_price": "402.00",
         *             "estimated_notional": "10050.00",
         *             "rationale": "20/50 EMA огтлолцол + өмнөх 3 өдрийн дундажаас 1.8 дахин их эзлэхүүн. Эх өгөгдөл нь доорх tool call-уудад бүрэн байна.",
         *             "grounded_in": [
         *               "11111111-2222-4333-8444-555555555555",
         *               "66666666-7777-4888-8999-aaaaaaaaaaaa"
         *             ],
         *             "provider": "claude-mcp",
         *             "model": "claude-opus-5"
         *           },
         *           "risk": {
         *             "decision": "ESCALATE_TO_HUMAN",
         *             "reason": "Notional 10050.00 > MAX_ORDER_NOTIONAL 5000.00",
         *             "evaluated_at": "2026-09-16T14:22:10Z",
         *             "checks": [
         *               {
         *                 "rule": "order_notional",
         *                 "passed": false,
         *                 "limit_name": "MAX_ORDER_NOTIONAL",
         *                 "limit_value": "5000.00",
         *                 "actual_value": "10050.00"
         *               },
         *               {
         *                 "rule": "position_pct",
         *                 "passed": true,
         *                 "limit_name": "MAX_POSITION_PCT",
         *                 "limit_value": "10",
         *                 "actual_value": "9.6"
         *               }
         *             ]
         *           },
         *           "created_at": "2026-09-16T14:22:10Z",
         *           "expires_at": "2026-09-16T14:37:10Z",
         *           "resolved_at": null,
         *           "resolution_reason": null
         *         }
         *       ]
         *     }
         */
        ApprovalsEnvelope: components["schemas"]["Envelope"] & {
            approvals: components["schemas"]["Approval"][];
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "groups": [
         *         {
         *           "origin": "research_agent",
         *           "origin_detail": "claude-mcp/claude-opus-5",
         *           "symbols": [
         *             {
         *               "symbol": "AAPL",
         *               "has_open_position": true,
         *               "position_qty": "40",
         *               "market_value": "9012.00",
         *               "open_order_count": 0,
         *               "origin_mixed": false,
         *               "last_decision_at": "2026-09-16T13:55:02Z",
         *               "last_decision_id": "3c9d8e7f-6a5b-4c3d-8e1f-0a9b8c7d6e5f"
         *             }
         *           ]
         *         },
         *         {
         *           "origin": "manual_operator",
         *           "origin_detail": "operator",
         *           "symbols": [
         *             {
         *               "symbol": "MSFT",
         *               "has_open_position": true,
         *               "position_qty": "12",
         *               "market_value": "4870.80",
         *               "open_order_count": 1,
         *               "origin_mixed": true,
         *               "last_decision_at": null,
         *               "last_decision_id": null
         *             }
         *           ]
         *         },
         *         {
         *           "origin": "external",
         *           "origin_detail": null,
         *           "symbols": [
         *             {
         *               "symbol": "TSLA",
         *               "has_open_position": true,
         *               "position_qty": "5",
         *               "market_value": "1252.50",
         *               "open_order_count": 0,
         *               "origin_mixed": false,
         *               "last_decision_at": null,
         *               "last_decision_id": null
         *             }
         *           ]
         *         }
         *       ]
         *     }
         */
        AttributionEnvelope: components["schemas"]["Envelope"] & {
            /** @description Origin тус бүрээр нэг бүлэг. Мөргүй origin бүлэг үүсгэхгүй. */
            groups: {
                origin: components["schemas"]["Origin"];
                origin_detail?: string | null;
                symbols: {
                    symbol: string;
                    has_open_position: boolean;
                    position_qty?: components["schemas"]["Quantity"];
                    market_value?: components["schemas"]["Money"];
                    open_order_count: number;
                    /** @description Symbol нь олон origin-той (LLD §11.1). Ийм symbol холбогдох БҮХ бүлэгт давхар гарна — далдлахгүй (LLD §16.4). Нийлбэр гаргахдаа давхардлыг тооцно. */
                    origin_mixed: boolean;
                    /** Format: date-time */
                    last_decision_at?: string | null;
                    /** Format: uuid */
                    last_decision_id?: string | null;
                }[];
            }[];
        };
        AgentDecision: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            agent: "research" | "auto_tuning";
            provider: string;
            model: string;
            created_at: components["schemas"]["Utc"];
            proposal: components["schemas"]["ProposedOrder"];
            risk: components["schemas"]["RiskEvaluation"];
            grounding?: {
                passed: boolean;
                /** @description Шалгагч ОГТ ажиллаагүй (жишээ нь `halted` үед санал эрт татгалзсан). Ийм үед `passed: false` нь «унасан» биш «шалгагдаагүй» гэсэн утгатай — UI хоёрыг ялгаж харуулна. */
                not_run?: boolean;
                /** @description Шалгагдсан тоон мэдэгдлийн тоо. */
                checked_claims?: number;
                /** @description Цитат tool call-ийн payload-д ОЛДООГҮЙ тоон мэдэгдлүүд. */
                unverified_claims?: string[];
            };
            /** @enum {string} */
            outcome: "grounding_failed" | "risk_rejected" | "awaiting_approval" | "approved" | "executed" | "order_failed";
            /** Format: uuid */
            order_id?: string | null;
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "decisions": [
         *         {
         *           "id": "3c9d8e7f-6a5b-4c3d-8e1f-0a9b8c7d6e5f",
         *           "agent": "research",
         *           "provider": "claude-mcp",
         *           "model": "claude-opus-5",
         *           "created_at": "2026-09-16T13:54:58Z",
         *           "proposal": {
         *             "symbol": "AAPL",
         *             "side": "buy",
         *             "qty": "10",
         *             "order_type": "limit",
         *             "limit_price": "221.50",
         *             "estimated_notional": "2215.00",
         *             "rationale": "Эзлэхүүнээр батлагдсан EMA огтлолцол",
         *             "grounded_in": [
         *               "11111111-2222-4333-8444-555555555555"
         *             ],
         *             "provider": "claude-mcp",
         *             "model": "claude-opus-5"
         *           },
         *           "risk": {
         *             "decision": "APPROVE",
         *             "reason": null,
         *             "evaluated_at": "2026-09-16T13:55:00Z",
         *             "checks": [
         *               {
         *                 "rule": "order_notional",
         *                 "passed": true,
         *                 "limit_name": "MAX_ORDER_NOTIONAL",
         *                 "limit_value": "5000.00",
         *                 "actual_value": "2215.00"
         *               }
         *             ]
         *           },
         *           "grounding": {
         *             "passed": true,
         *             "unverified_claims": []
         *           },
         *           "outcome": "executed",
         *           "order_id": "6f1b5a2c-0d4e-4f31-9b77-1a2c3d4e5f60"
         *         }
         *       ]
         *     }
         */
        AgentDecisionsEnvelope: components["schemas"]["Envelope"] & {
            decisions: components["schemas"]["AgentDecision"][];
        };
        AgentDecisionDetail: components["schemas"]["Envelope"] & {
            decision: components["schemas"]["AgentDecision"];
            tool_calls: {
                /** Format: uuid */
                id: string;
                tool_name: string;
                request: {
                    [key: string]: unknown;
                };
                /** @description Alpaca-аас ирсэн ТҮҮХИЙ хариу (зөвхөн redaction) */
                response: {
                    [key: string]: unknown;
                };
                source: components["schemas"]["Source"];
                called_at: components["schemas"]["Utc"];
                latency_ms?: number;
            }[];
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "providers": [
         *         {
         *           "id": "claude-mcp",
         *           "vendor": "anthropic",
         *           "model": "claude-opus-5",
         *           "transport": "mcp",
         *           "healthy": true,
         *           "read_only": false,
         *           "last_error": null
         *         },
         *         {
         *           "id": "gpt-fc",
         *           "vendor": "openai",
         *           "model": "gpt-5",
         *           "transport": "function_calling",
         *           "healthy": true,
         *           "read_only": false,
         *           "last_error": null
         *         },
         *         {
         *           "id": "local-fallback",
         *           "vendor": "local",
         *           "model": "llama-3.1-70b",
         *           "transport": "stdio_json",
         *           "healthy": true,
         *           "read_only": true,
         *           "last_error": null
         *         }
         *       ],
         *       "active": {
         *         "research": "claude-mcp",
         *         "auto_tuning": "gpt-fc"
         *       }
         *     }
         */
        ProvidersEnvelope: components["schemas"]["Envelope"] & {
            providers: {
                /** @example claude-mcp */
                id: string;
                /** @enum {string} */
                vendor: "anthropic" | "openai" | "xai" | "opencode" | "local";
                model: string;
                /** @enum {string} */
                transport: "mcp" | "function_calling" | "stdio_json";
                healthy: boolean;
                /**
                 * @description Local / fallback provider-ууд анхдагчаар `true` — тэдэнд
                 *     `propose_order` НЭЭГДЭХГҮЙ (хавсралт 05 §2).
                 */
                read_only: boolean;
                last_error?: string | null;
            }[];
            /** @description role → provider_id (жишээ: `{"research": "claude-mcp"}`) */
            active: {
                [key: string]: string;
            };
        };
        ProviderSwitchResult: components["schemas"]["Envelope"] & {
            role: string;
            previous_provider_id: string;
            new_provider_id: string;
            /** @description Хуучин provider-оор дуусах tool call-ийн тоо. Тэдгээр нь ХУУЧНААР бүртгэгдэнэ. */
            in_flight_calls: number;
            switched_at: components["schemas"]["Utc"];
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "parameters": [
         *         {
         *           "name": "STOP_LOSS_PCT",
         *           "current_value": "2.5",
         *           "bounds": {
         *             "min": "1.0",
         *             "max": "5.0",
         *             "step": "0.1"
         *           },
         *           "applies_to": "paper",
         *           "history": [
         *             {
         *               "id": "aaaabbbb-cccc-4ddd-8eee-ffff00001111",
         *               "old_value": "2.4",
         *               "new_value": "2.5",
         *               "changed_at": "2026-09-15T21:05:00Z",
         *               "approved_by": "system",
         *               "backtest_window": {
         *                 "start": "2026-06-01",
         *                 "end": "2026-09-14"
         *               },
         *               "walk_forward": {
         *                 "folds": 6,
         *                 "in_sample_metric": "sharpe=1.31",
         *                 "out_of_sample_metric": "sharpe=1.08"
         *               }
         *             }
         *           ]
         *         }
         *       ]
         *     }
         */
        TuningEnvelope: components["schemas"]["Envelope"] & {
            parameters: {
                name: string;
                current_value: string;
                bounds: {
                    min: string;
                    max: string;
                    step: string;
                };
                /**
                 * @description Анхдагчаар `paper`. `live` болох цорын ганц зам = `POST /tuning/promote`.
                 * @enum {string}
                 */
                applies_to: "backtest" | "paper" | "live";
                history?: {
                    /** Format: uuid */
                    id: string;
                    old_value: string;
                    new_value: string;
                    changed_at: components["schemas"]["Utc"];
                    /** @enum {string} */
                    approved_by: "system" | "operator";
                    backtest_window?: {
                        /** Format: date */
                        start?: string;
                        /** Format: date */
                        end?: string;
                    };
                    walk_forward: {
                        folds: number;
                        in_sample_metric: string;
                        out_of_sample_metric: string;
                    };
                }[];
            }[];
        };
        /**
         * @example {
         *       "source": "alpaca_paper",
         *       "as_of": "2026-09-16T14:30:00Z",
         *       "stale": false,
         *       "system_state": "active",
         *       "state": "active",
         *       "reason": null,
         *       "changed_at": "2026-09-16T09:00:00Z",
         *       "changed_by": "operator",
         *       "wind_down_deadline": null,
         *       "seconds_remaining": null,
         *       "breaker_metrics": [
         *         {
         *           "metric": "daily_loss",
         *           "value": "-312.44",
         *           "limit_name": "MAX_DAILY_LOSS",
         *           "limit_value": "-2000.00",
         *           "tripped": false
         *         },
         *         {
         *           "metric": "api_error_rate",
         *           "value": "0.004",
         *           "limit_name": "MAX_API_ERROR_RATE",
         *           "limit_value": "0.05",
         *           "tripped": false
         *         }
         *       ]
         *     }
         */
        SystemStateEnvelope: components["schemas"]["Envelope"] & {
            state: components["schemas"]["SystemState"];
            reason?: string | null;
            changed_at: components["schemas"]["Utc"];
            /** @enum {string} */
            changed_by: "operator" | "circuit_breaker" | "scheduler";
            /**
             * Format: date-time
             * @description Зөвхөн `winding_down` үед. Дуусахад `halted`.
             */
            wind_down_deadline?: string | null;
            seconds_remaining?: number | null;
            /**
             * @description Circuit breaker-ийн метрик бүрийн одоогийн байдал. `activate`
             *     энэ жагсаалтыг ДАХИН хэмжиж шийднэ — хадгалагдсан туг биш.
             */
            breaker_metrics?: {
                /** @enum {string} */
                metric: "daily_loss" | "api_error_rate" | "order_reject_rate" | "ws_disconnects";
                value: string;
                limit_name: string;
                limit_value: string;
                tripped: boolean;
            }[];
        };
        /** @description RFC 9457 Problem Details. */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            /** @enum {string} */
            code: "confirmation_required" | "system_halted" | "winding_down_increase_blocked" | "risk_rejected" | "grounding_failed" | "idempotency_conflict" | "breaker_still_tripped" | "already_active" | "approval_expired" | "version_conflict" | "broker_unavailable" | "provider_unavailable" | "not_found";
            detail?: string;
            risk?: components["schemas"]["RiskEvaluation"];
            /** @description Зөвхөн `confirmation_required` үед. Хоёр шаттай баталгаажуулалтын сорилт. */
            confirmation?: {
                token: string;
                /**
                 * @description Operator-т харуулах тодорхой текст. Үйлдэл тус бүрд ӨӨР —
                 *     хоёр товчийг андуурахаас сэргийлнэ (AC-38).
                 */
                prompt: string;
                expires_at: components["schemas"]["Utc"];
            };
            breaker_metrics?: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: {
        /** @description Олдсонгүй */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Alpaca хүрэхгүй байна. Систем таамаглахгүй — хуучин утгыг live мэт
         *     буцаахгүй. Frontend үүнийг «stale» banner болгоно.
         */
        BrokerUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description Клиент үүсгэнэ. Энэ утга нь `client_order_id`-ийн үндэс болно.
         *     Ижил key + ижил бие = ижил хариу, давхар order БАЙХГҮЙ.
         *     Ижил key + өөр бие = 409 `idempotency_conflict`.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Эрүүл. `degraded` байж болно — статус кодоор биш, биеэр нь заана. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountEnvelope"];
                };
            };
            503: components["responses"]["BrokerUnavailable"];
        };
    };
    getPositions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsEnvelope"];
                };
            };
            503: components["responses"]["BrokerUnavailable"];
        };
    };
    getQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteEnvelope"];
                };
            };
            503: components["responses"]["BrokerUnavailable"];
        };
    };
    getOrders: {
        parameters: {
            query?: {
                status?: "open" | "closed" | "all";
                symbol?: string;
                origin?: components["schemas"]["Origin"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersEnvelope"];
                };
            };
        };
    };
    postOrdersManual: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Клиент үүсгэнэ. Энэ утга нь `client_order_id`-ийн үндэс болно.
                 *     Ижил key + ижил бие = ижил хариу, давхар order БАЙХГҮЙ.
                 *     Ижил key + өөр бие = 409 `idempotency_conflict`.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualOrderRequest"];
            };
        };
        responses: {
            /** @description Risk дамжсан, Execution-д хүлээн авсан */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderAccepted"];
                };
            };
            /**
             * @description Баталгаажуулалт шаардлагатай (`confirmation_required`), эсвэл
             *     систем `halted` (`system_halted`), эсвэл `Idempotency-Key`
             *     давхардсан боловч бие өөр (`idempotency_conflict`).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Risk Agent татгалзав (`risk_rejected`) — шалтгаан биед */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    postOrdersByOrderIdCancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Цуцлах хүсэлт Alpaca руу илгээгдэв */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAttribution: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributionEnvelope"];
                };
            };
        };
    };
    getApprovals: {
        parameters: {
            query?: {
                state?: "pending" | "approved" | "rejected" | "expired" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalsEnvelope"];
                };
            };
        };
    };
    postApprovalsByApprovalIdApprove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approvalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Optimistic lock. `GET /approvals`-аас авсан `version`.
                     *     Зөрвөл 409 — TTL дуусаад `expired` болсон мөрийг
                     *     зөвшөөрөх боломжгүй (AC-6).
                     */
                    expected_version: number;
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Зөвшөөрөгдөв, Execution-д дамжив */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderAccepted"];
                };
            };
            /** @description Мөр аль хэдийн шийдэгдсэн / `expired` / версийн зөрүү */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    postApprovalsByApprovalIdReject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approvalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expected_version: number;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Татгалзав. Энэ санал ХЭЗЭЭ Ч илгээгдэхгүй. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Мөр аль хэдийн шийдэгдсэн эсвэл версийн зөрүү */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getAgentDecisions: {
        parameters: {
            query?: {
                agent?: "research" | "auto_tuning";
                symbol?: string;
                outcome?: components["schemas"]["RiskDecision"];
                provider?: string;
                since?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDecisionsEnvelope"];
                };
            };
        };
    };
    getAgentDecisionsByDecisionId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentDecisionDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersEnvelope"];
                };
            };
        };
    };
    postProvidersByRoleSwitch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role: "research";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description `GET /providers`-ийн `id` (жишээ: `claude-mcp`, `openai-fc`) */
                    provider_id: string;
                };
            };
        };
        responses: {
            /** @description Солигдов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSwitchResult"];
                };
            };
            /** @description Тохируулагдаагүй эсвэл эрүүл мэндийн шалгалт унасан provider */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getTuningParameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TuningEnvelope"];
                };
            };
        };
    };
    postTuningPromote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    tuning_history_ids: string[];
                    confirmation_token?: string;
                };
            };
        };
        responses: {
            /** @description Дэвшүүлэв. `tuning_history`-д `approved_by=operator`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Баталгаажуулалт шаардлагатай, эсвэл walk-forward нотолгоо дутуу */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSystemState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStateEnvelope"];
                };
            };
        };
    };
    postKillSwitch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Зогссон */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "source": "alpaca_paper",
                     *       "as_of": "2026-09-16T14:31:00Z",
                     *       "stale": false,
                     *       "system_state": "halted",
                     *       "state": "halted",
                     *       "reason": "Operator kill switch",
                     *       "changed_at": "2026-09-16T14:31:00Z",
                     *       "changed_by": "operator",
                     *       "wind_down_deadline": null,
                     *       "seconds_remaining": null,
                     *       "breaker_metrics": []
                     *     }
                     */
                    "application/json": components["schemas"]["SystemStateEnvelope"];
                };
            };
        };
    };
    postSystemWindDown: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wind-down эхлэв */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "source": "alpaca_paper",
                     *       "as_of": "2026-09-16T14:30:00Z",
                     *       "stale": false,
                     *       "system_state": "winding_down",
                     *       "state": "winding_down",
                     *       "reason": "Operator: машинаа унтраах гэж байна",
                     *       "changed_at": "2026-09-16T14:30:00Z",
                     *       "changed_by": "operator",
                     *       "wind_down_deadline": "2026-09-16T14:45:00Z",
                     *       "seconds_remaining": 900,
                     *       "breaker_metrics": []
                     *     }
                     */
                    "application/json": components["schemas"]["SystemStateEnvelope"];
                };
            };
            /** @description Аль хэдийн `halted` — wind-down утгагүй */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    postSystemActivate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    confirmation_token?: string;
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Идэвхжив */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStateEnvelope"];
                };
            };
            /**
             * @description `confirmation_required` — token дутуу; эсвэл
             *     `breaker_still_tripped` — метрик нэрлэгдэнэ; эсвэл
             *     `already_active`.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
